name: robust-speech-commands
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10.19
  - pip=25.3

  # Audio DSP
  - numpy=1.26.4
  - scipy=1.15.2
  - librosa=0.11.0

  # Configuration
  - hydra-core=1.3.2

  # Utilities
  - matplotlib=3.10.8
  - pandas=2.3.3
  - tqdm=4.67.1

  # Needed by  tf-datasets
  - pydub=0.25.1
  - ffmpeg=8.0.1

  - pip:
    # ML and data
    - tensorflow==2.15.0
    - tensorflow-datasets==4.9.9

    # Audio libraries
    - soundfile==0.13.1
    - sounddevice==0.5.3
